spring:
  datasource:
    password: '@Teste123'
    username: 'teste'
    url: jdbc:mysql://localhost:3306/alurafood_payment?createDatabaseIfNotExist=true&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

