spring:
  application:
    name: 'payments'

  datasource:
    password: '@Teste123'
    username: 'teste'
    url: jdbc:mysql://localhost:3306/alurafood_payments?createDatabaseIfNotExist=true&serverTimezone=UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s

server:
  port: 8080