
spring:
  application:
    name: 'orders'

  datasource:
    password: '@Teste123'
    username: 'teste'
    url: jdbc:mysql://localhost:3306/alurafood_orders?createDatabaseIfNotExist=true&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 0