
spring:
  application:
    name: 'orders'

  datasource:
    password: '@Teste123'
    username: 'teste'
    url: jdbc:mysql://localhost:3306/alurafood_orders?createDatabaseIfNotExist=true&serverTimezone=UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          max-interval: 300000
          multiplier: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${random.int}

server:
  port: 8081