server:
  port: 8082

spring:
  application:
    name: 'gateway'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    statusPageUrlPath: ${eureka.instance.hostname}/info
    healthCheckUrlPath: ${eureka.instance.hostname}/health