
spring:
  application:
    name: 'reviews'

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          max-interval: 300000
          multiplier: 2

server:
  port: 8083